:schedule:
  # set up a schedule for each portal
  test_portal:
    cron: '* * * * *'   # Runs once per minute
    class: GetPortalDataJob
    queue: high
    args: ['Portals::TestPortal']

:concurrency: 5
:queues:
  - high
